-- Datos de ejemplo para Directorio Gaymers
-- Ejecuta este archivo despues de supabase_schema.sql

begin;

insert into public.members (
    full_name,
    nickname,
    age,
    sexuality,
    height_cm,
    location,
    favorite_color,
    favorite_food,
    favorite_movies,
    music_tastes,
    hobbies,
    zodiac_sign,
    favorite_character,
    gaming_system,
    currently_playing,
    instagram,
    birthday,
    photo_bytes,
    photo_mime_type
)
values
(
    'Christian',
    'Kriz',
    36,
    'homosensual',
    172,
    'El Retiro, Guadalajara',
    'Rojo',
    'Pizza y mole',
    'Terror',
    'Pop, Daft Punk',
    'Tatuador, videojuegos, patinar',
    'Piscis',
    'Samus, Bowser Jr',
    'Nintendo Switch',
    'FF12, Pokemon Champions',
    '@kriz_chr',
    '26 de febrero',
    null,
    null
),
(
    'Alexis Romero',
    'Lex',
    29,
    'gay',
    178,
    'Zapopan, Jalisco',
    'Azul',
    'Ramen y tacos',
    'Ciencia ficcion',
    'Synthwave, pop',
    'Gym, gaming, series',
    'Leo',
    'Link',
    'PC',
    'Helldivers 2, Baldur''s Gate 3',
    '@lex.play',
    '14 de agosto',
    null,
    null
),
(
    'Mauricio Perez',
    'Mau',
    32,
    'bi',
    170,
    'Monterrey, Nuevo Leon',
    'Verde',
    'Sushi',
    'Animacion',
    'K-pop, electro',
    'Bailar, dibujar, videojuegos',
    'Geminis',
    'Kirby',
    'PlayStation 5',
    'Final Fantasy VII Rebirth',
    '@maubits',
    '3 de junio',
    null,
    null
),
(
    'Diego Salas',
    'Dix',
    27,
    'gay',
    181,
    'CDMX',
    'Negro',
    'Hamburguesas',
    'Accion y fantasia',
    'Rock alternativo',
    'Streaming, correr, videojuegos',
    'Aries',
    'Cloud Strife',
    'Xbox Series X',
    'Elden Ring',
    '@dixmode',
    '9 de abril',
    null,
    null
),
(
    'Sergio Luna',
    'Checo',
    34,
    'homosensual',
    175,
    'Puebla',
    'Morado',
    'Chilaquiles',
    'Comedia romantica',
    'Indie pop',
    'Cocinar, cantar, Nintendo',
    'Tauro',
    'Princess Peach',
    'Nintendo Switch',
    'Animal Crossing, Mario Kart 8',
    '@checoluna',
    '1 de mayo',
    null,
    null
);

commit;
